services:

  spark:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.spark
    container_name: spark-streaming

    volumes:
      - ./:/app
      - C:\Users\user\AppData\Roaming\gcloud:/root/.config/gcloud

    environment:
      - GOOGLE_CLOUD_PROJECT=meli-data-platform
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json

    working_dir: /app
    command: tail -f /dev/null # el contenedor no hace nada solo se queda vivo esperando comandos, airflow entra con el comando docker exc spark-streaming


  airflow:
    image: apache/airflow:2.9.1
    container_name: airflow

    ports:
      - "8081:8080"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./models:/opt/airflow/models
      - C:\Users\user\AppData\Roaming\gcloud\application_default_credentials.json:/opt/airflow/creds/gcp-creds.json
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/creds/gcp-creds.json

    command: airflow standalone


  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.api
    container_name: meli-api

    ports:
      - "8000:8000"

    volumes:
      - ./:/app
      - C:\Users\user\AppData\Roaming\gcloud\application_default_credentials.json:/app/creds/gcp-creds.json

    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/creds/gcp-creds.json

    depends_on:
      - spark
      - airflow