services:

  spark:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: spark-streaming

    volumes:
      - ../:/app
      - C:\Users\user\AppData\Roaming\gcloud:/root/.config/gcloud

    environment:
      - GOOGLE_CLOUD_PROJECT=meli-data-platform

    working_dir: /app
    command: tail -f /dev/null # el contenedor no hace nada solo se queda vivo esperando comandos, airflow entra con el comando docker exc spark-streaming


  airflow:
    image: apache/airflow:2.9.1
    container_name: airflow

    ports:
      - "8081:8080"

    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - C:\Users\user\AppData\Roaming\gcloud:/root/.config/gcloud
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False

    command: airflow standalone